name: Release Insiders

on:
  push:
    branches:
      - githubActions-learn
  pull_request:
    branches:
      - develop
    types: [closed]

env:
  NODE_VERSION: 20
  RELEASE_CHANNEL: insiders
  VERSION: 0.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      # - name: Install dependencies
      #   run: npm install

      # - name: Use linter
      #   run: npm run lint

      # - name: Build mytril
      #   run: npm run build

  prerelease:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    outputs:
      version_release: ${{ steps.set_version.outputs.version_release }}
      sha_short: ${{ steps.get_sha_version.outputs.version_release }}

    steps:
      - uses: actions/checkout@v4

      - name: Resolve version
        id: get_sha_version
        run: |
          echo "sha_version=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Generate version
        id: set_version
        run: |
          sha_version="${{ steps.get_sha_version.outputs.sha_version }}"
          echo "version_release=${${VERSION}-${RELEASE_CHANNEL}.${sha_version}}" >> $GITHUB_OUTPUT
          # full_version="${VERSION}-${RELEASE_CHANNEL}.${sha_version}"
          # echo "Generated Version: $full_version"
          # echo "version_release=${full_version}" >> $GITHUB_OUTPUT

  publish:
    runs-on: ubuntu-latest
    needs: prerelease
    env:
      version_release: ${{ needs.prerelease.outputs.version_release }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Version
        run: echo "The current branch is => ${{ env.version_release }}"
      # - name: Install dependencies
      #   run: npm install

      # - name: Force v0.0.0 to mytril
      #   run: npm version 0.0.0 -f

      # - name: New prerelease version
      #   run: npm version prerelease --preid=insiders --no-git-tag-version

      # - name: Authenticate to NPM
      #   run: |
      #     echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc

      # - name: Build
      #   run: npm run build

      # - name: Verify files
      #   run: npm pack --dry-run

      # - name: Inspect the working tree
      #   run: echo "The current branch is => ${{ env.version_release }}"

      # - name: Publish to NPM
      #   run: |
      #     echo "Publishing version ${{ env.version_release }}"
      #     npm publish --tag insiders
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
