name: Publish to NPM on Dev branch

on:
  push:
    branches:
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1 : Check repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2 : Config Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3 : install and build
      - name: Install dependencies
        run: npm install

      # Step 4 : Get local version
      - name: Get version from NPM
        id: get_npm_version
        run: |
          PACKAGE_NAME="mytril"
          NPM_VERSION=$(npm show $PACKAGE_NAME version || echo "0.0.0")
          echo "npm_version=$NPM_VERSION" >> $GITHUB_ENV
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      # Step 5 : Verify version on NPM
      - name: Compare versions
        id: compare_versions
        run: |
          LOCAL_VERSION=$(node -p "require('./package.json').version")
          echo "Local version: $LOCAL_VERSION"
          echo "NPM version: $NPM_VERSION"

          if [ "$(printf '%s\n' "$NPM_VERSION" "$LOCAL_VERSION" | sort -V | tail -n1)" != "$LOCAL_VERSION" ]; then
            echo "Local version is not greater than NPM version. Skipping publication."
            exit 0
          else
            echo "Local version is greater than NPM version. Proceeding to publish."
          fi

        env:
          NPM_VERSION: ${{ env.npm_version }}

      # Step 6: Publish on NPM
      - name: Publish to NPM
        if: steps.compare_versions.outcome == 'success'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
