name: Release Insiders

on:
  push:
    branches:
      - svelte-5

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1 : Check repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2 : Config Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3 : Install and build Mytril
      - name: Install dependencies
        run: npm install

  lint:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1 : Check repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2 : Config Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3 : Install and build Mytril
      - name: Install dependencies
        run: npm install

      # Step 4 : Run linter
      - name: Run linter
        run: npm run lint

  prepublish:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      # Step 1 : Check repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2 : Config Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3 : Install and build Mytril
      - name: Install dependencies
        run: npm install

      # Step 4 : Update prerelease version
      - name: Bump prerelease version
        run: npm version prerelease --preid=insiders
        env:
          CI: true

      # Step 5 : Publish mytril with tag insiders
      - name: Publish to NPM
        run: npm publish --tag insiders
