name: Release Insiders

on:
  push:
    branches:
      - svelte-5
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

  prepublish:
    runs-on: ubuntu-latest
    needs: test

    outputs:
      new-version: ${{ steps.set_version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Commit & Push version change
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json package-lock.json
          git commit -m "New insiders version"
          git push origin svelte-5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: New prerelease version
        id: set_version
        run: |
          version=$(npm version prerelease --preid=insiders)
          echo "New version: $version"
          echo "::set-output name=version::$version"

  publish:
    runs-on: ubuntu-latest
    needs: prepublish

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Authenticate to NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc

      - name: Build
        run: npm run build

      - name: Verify files
        run: npm pack --dry-run

      - name: Publish to NPM
        run: |
          echo "Publishing version ${{ needs.prepublish.outputs.new-version }}"

        env:
          NODE_AUTH_TOKEN:
            ${{ secrets.NPM_AUTH_TOKEN }}

            #  npm publish --tag insiders
