name: Release Insiders

on:
  push:
    branches:
      - svelte-5

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1 : Check repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      # Step 2 : Config Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3 : Install and build Mytril
      - name: Install dependencies
        run: npm install

      # Step 4 : Save dependencies
      - name: Upload dependencies
        uses: actions/upload-artifact@v3
        with:
          name: node-modules
          path: node_modules/

  lint:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1 : Check repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      # Step 2 : Load dependencies
      - name: Download dependencies
        uses: actions/download-artifact@v3
        with:
          name: node-modules
          path: node_modules/

      # Step 2 : Run linter
      - name: Run linter
        run: npm run lint
