name: Release Insiders

on:
  push:
    branches:
      - search-cli-svelte-5

jobs:
  prepublish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: New prerelease version
        run: npm version prerelease --preid=insiders --no-git-tag-version

      - name: Inspect the working tree
        run: |
          echo "Inspecting Git status and diff..."
          git status
          git diff

      - name: Commit & Push version change
        if: github.event_name == 'push'
        run: |
          git branch --show-current
          git commit -a -m "New insiders version"
        # git status
        # git fetch origin
        # git rebase --strategy-option=theirs origin/search-cli-svelte-5 --verbose
        # git push
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
